#!/bin/bash
# Author: Cangsheng Sheng
# Email: shencangsheng@126.com
# Created: 2024-06-10
# Version: 1.0

source ./tools

function mirror_maven_install() {
    echo '' >.env

    if contains_args "--magic"; then

        if [ ! -f "$_PWD/magic/.env" ]; then
            Error "Need to install magic. exec: ./ctl magic hlep"
            exit 1
        fi

        source $_PWD/magic/.env

        cat <<EOF >.env
MAGIC_ENABLE="TRUE"
MAGIC_USERNAME="$MAGIC_USERNAME"
MAGIC_PASSWORD="$MAGIC_PASSWORD"
EOF

    fi
    docker compose up -d

    cat <<EOF
    http address - http://0.0.0.0:18081/
EOF
}

function mirror_maven_uninstall() {
    docker compose down
}

function mirror_maven_help() {
    cat <<EOF

  Usage: ./ctl maven [OPTION...]

  Examples:
        ./ctl maven install # Install Maven registry
        ./ctl maven install --magic # Install Maven registry, enable proxy
        ./ctl maven uninstall # Uninstall Maven registry
        ./ctl maven join # Show using registry
        ./ctl maven magic # Configuration magic, @deprecated
        ./ctl maven status # Show Maven status
        ./ctl maven clean # Clean out
        ./ctl maven user # Show registry default user
        ./ctl maven start # start
        ./ctl maven stop # stop
        ./ctl maven restart # restart
EOF
}

function mirror_maven_join() {
    local content=$(
        cat <<EOF

    Methods to Set Custom Registry

    Options:

    1. pom.xml

    <repositories>
    $_GREEN
        <repository>
            <id>private-nexus</id>
            <url>http://xx.xx.xx.xx:18081/repository/maven-public/</url>
        </repository>
    $_NC    
    </repositories>
    
    2. settings.xml

    <mirrors>
    $_GREEN
        <mirror>
            <id>Nexus</id>
            <name>Nexus</name>
            <mirrorOf>central</mirrorOf>
            <url>http://xx.xx.xx.xx:18081/repository/maven-public/</url>
        </mirror>
    $_NC
    </mirrors>

EOF
    )
    echo -e "$content"
}

function mirror_maven_magic() {
    local content=$(
        cat <<EOF

    作者已经找到安装部署时自动配置代理的方法，如果之前已经安装了并且未开启代理，则可以使用此方法手动配置;

    step-1: 
        访问 http://xx.xx.xx.xx:18081
    
    step-2:
        右上角: ${_GREEN}Sign in${_NC}
        账号：admin
        密码：执行 ${_GREEN}docker exec -it mirror-maven-maven-registry-1 sh -c "cat /nexus-data/admin.password"${_NC} 来获取

    step-3:
        左上角: ${_GREEN}Config${_NC}
    
    step-4:
        System -> HTTP -> Proxy Settings

    step-5:
        配置 Host 与 Authentication

        HTTP Proxy Host: magic
        HTTP Proxy Port: 7890
        HTTP Authentication Username: user
        HTTP Authentication Password: 执行 ${_GREEN}./ctl magic auth ${_NC}来获取

        HTTPS Proxy Host: magic
        HTTPS Proxy Port: 7890
        HTTPS Authentication Username: user
        HTTPS Authentication Password: 执行 ${_GREEN}./ctl magic auth ${_NC}来获取
        
EOF
    )
    echo -e "$content"
}

function mirror_maven_status() {
    local content=$(
        cat <<EOF
    ● maven.service
      $(get_service_status)
EOF
    )
    echo -e "$content"
}

function mirror_maven_clean() {
    mirror_maven_uninstall
    del_docker_vol 'mirror-maven-vol'
}

function mirror_maven_user() {
    local password=$(docker compose exec maven-registry sh -c 'cat /nexus-data/admin.password || echo "默认密码已被更改"')
    cat <<EOF
    user: admin
    password: $password
EOF
}

function mirror_maven_stop() {
    docker compose down
}

function mirror_maven_start() {
    docker compose up -d
}

function mirror_maven_restart() {
    mirror_maven_stop
    mirror_maven_start
}
