#!/bin/bash
# Author: Cangsheng Sheng
# Email: shencangsheng@126.com
# Created: 2024-06-10
# Version: 1.0

source ./tools

function mirror_npm_install() {
    cp -n example/config.yaml conf/config.yaml

    echo '' >.env

    if contains_args "--magic"; then

        if [ ! -f "$_PWD/magic/.env" ]; then
            Error "Need to install magic. exec: ./ctl magic hlep"
            exit 1
        fi

        source $_PWD/magic/.env

        cat <<EOF >.env
HTTP_PROXY="http://$MAGIC_USERNAME:$MAGIC_PASSWORD@magic:7890"
HTTPS_PROXY="http://$MAGIC_USERNAME:$MAGIC_PASSWORD@magic:7890"
NO_PROXY="localhost,127.0.0.1"
EOF
    fi

    docker compose up -d
}

function mirror_npm_uninstall() {
    docker compose down
}

function mirror_npm_help() {
    cat <<EOF

  Usage: ./ctl npm [OPTION...]

  Examples:
        ./ctl npm install # Install npm registry
        ./ctl npm install --magic # Install npm registry, enable proxy
        ./ctl npm uninstall # Uninstall npm registry
        ./ctl npm join # Show using registry
        ./ctl npm status # Show npm status
        ./ctl npm clean # Clean out
        ./ctl npm start # start
        ./ctl npm stop # stop
        ./ctl npm restart # restart
        ./ctl npm fastest # Set the fastest registry.
EOF
}

function mirror_npm_join() {
    local content=$(
        cat <<EOF

    Methods to Set Custom Registry

    Options:

    1. Using Command Line Parameter

    $_GREEN
    npm install --registry=http://xx.xx.xx.xx:14873 lodash
    yarn install lodash --registry http://xx.xx.xx.xx:14873
    $_NC

    2. Using npm Config Command

    $_GREEN
    npm config set registry http://xx.xx.xx.xx:14873
    npm install lodash
    $_NC

    3. Using yarn Config Command

    $_GREEN
    yarn config set registry http://xx.xx.xx.xx:14873
    yarn install lodash
    $_NC

EOF
    )
    echo -e "$content"
}

function mirror_npm_status() {
    local content=$(
        cat <<EOF
    ● npm.service
      $(get_service_status)
EOF
    )
    echo -e "$content"
}

function mirror_npm_clean() {
    mirror_npm_uninstall
    del_docker_vol 'mirror-npm-vol'
}

function mirror_npm_stop() {
    docker compose down
}

function mirror_npm_start() {
    docker compose up -d
}

function mirror_npm_restart() {
    mirror_npm_stop
    mirror_npm_start
}

function mirror_npm_fastest_registry() {
    local registry=$(get_fast_registry 'npm' 'https://registry.npmjs.org/')

    sed -i "s|url: \".*\"|url: \"$registry\"|" ./conf/config.yaml

    docker compose restart

    Info "Successfully switched to: $registry"
}
