version: "3"
services:
  maven-registry:
    image: sonatype/nexus3:3.69.0
    restart: always
    ports:
      - "18081:8081"
    volumes:
      - mirror-maven-vol:/nexus-data
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    networks:
      - magic-network
    env_file:
      - .env
    entrypoint: /docker-entrypoint.sh
volumes:
  mirror-maven-vol:
    external: true
networks:
  magic-network:
    external: true
