version: "3"
services:
  pypi-registry:
    image: sonatype/nexus3:3.69.0
    restart: always
    ports:
      - "18082:8081"
    volumes:
      - mirror-pypi-vol:/nexus-data
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    networks:
      - magic-network
    env_file:
      - .env
    entrypoint: /docker-entrypoint.sh
volumes:
  mirror-pypi-vol:
    external: true
networks:
  magic-network:
    external: true
